Main
OpenDevUFCG/andromedev pull request #55
Opened 2021-10-01 02:49 UTC by jonathasbsouza

#47

#### Qual o propósito dessa pull request?

#### O que foi feito?

Criação do componente `<ScheduleCard>` que exibe os eventos do site.
Possui dois estados, um base e outro ativo quando o evento é no dia atual.

#### Como suas mudanças podem ser testadas?

Inseri os cards nas duas variações na home do projeto.

#### Screenshots ou exemplos de uso

<img width="1065" alt="Screen Shot 2021-09-30 at 23 49 17" src="https://user-images.githubusercontent.com/7189694/135557910-03f336f8-8e28-441c-affc-6ec643191312.png">

#### Tipo de mudanças

- [ ] Conserta bug
- [ x ] Nova funcionalidade

2021-10-01 13:30 UTC, JoseRenan requested changes
@jonathasbsouza, ficou TOPPPPPP ❤️ mto obg!!! Comentei umas besteirinhas de tipagem e reuso, mas de resto tá TOP TOP TOP!

2021-10-01 13:30 UTC, JoseRenan commented on src/components/home/ScheduleCard.tsx
> +    variant: string
No typescript tu consegue especificar ainda mais quais strings tu aceita como `variant`, tipo, dá forma que tá, o typescript vai permitir que eu passe qualquer string pra cá, sendo que o ideal seria só ser possível passar as strings referentes a variante, certo?

pra fazer isso, tu faz: 
```suggestion
    variant: 'base' | 'today'
```

e aí se tu tentar passar a string `'bas'` como prop, o typescript vai reclamar, pq só aceita `base` ou `today`

2021-10-01 13:30 UTC, JoseRenan commented on src/components/home/ScheduleCard.tsx
> +    variant: string
Outra coisa, eu tava pensando em algum nome que ficasse mais genérico, pra esse componente poder ser reusado em outros lugares, algo como ActiveableCard, ou alguma coisa que remetesse que ele pode ser ativo ou highlighted 🤔 e aí isso mudaria tbm qual são as variantes, algo como `base` e `active` ou `highlighted` alguma coisa assim, oq tu acha?

2021-10-01 13:30 UTC, JoseRenan commented on src/components/home/ScheduleCard.tsx
> +  }
Acho que isso aqui poderia ser movido pra fora desse componente, pra gente conseguir exportar e usar em outros componentes depois, pq como ele tá sendo criado dentro de `ScheduleCard`, a gente não conseguiria nem exportar ele, só o ScheduleCard conseguiria usar, e como se trata de um componente que usa um estilo global só pra ele, faz sentido que outros componentes possam ter acesso também

2021-10-01 13:30 UTC, JoseRenan commented on src/components/home/ScheduleCard.tsx
> +    variant,
Tu pode definir um valor default no destructuring, pra caso a variant nn seja passada, assim:
```suggestion
    variant = 'base',
```

Ah, é importante que faz sentido também, na interface, colocar o variant como opcional (com `?`) quando a gente tem um valor default

2021-10-01 13:30 UTC, JoseRenan commented on src/pages/index.tsx
> +      </Stack>
Comentário só pra lembrar de remover isso quando for merjar (pode deixar que eu removo quando for merjar) pq preciso disso pra ver como tá por enquanto kkkkkkkkk

2021-10-01 13:30 UTC, JoseRenan commented on src/lib/theme/scheduleCard.ts
> +    width: '25vw',
usar `vw` aqui é uma boa ideia? acredito que em telas muito largas vai ficar muito enorme e em celulares vai ficar tamanhim de nada 🤔 acho que talvez seja melhor a gente ter tamanhos distintos pra cada tamanho de dispositivo pra deixar responsivo, acho que até fixos pra cada dispositivo possa fazer sentido 🤔 dá uma olhada [aqui](https://chakra-ui.com/docs/features/responsive-styles) como o chakra faz responsividade

2021-10-01 13:30 UTC, JoseRenan commented on src/components/home/ScheduleCard.tsx
> +            Mais informações @andromedev
Colocando isso aqui só pra lembrar de perguntar ao pessoal se esse `@andromedev` tem que linkar pra o instagram, twitter alguma coisa desse tipo 🤔 pq no caso, seria `@OpenDevUFCG` ao invés de andromedev 🤔

2021-10-01 14:04 UTC, jonathasbsouza commented on src/lib/theme/scheduleCard.ts
> +    width: '25vw',
:done:

2021-10-01 14:04 UTC, jonathasbsouza commented on src/components/home/ScheduleCard.tsx
> +    variant,
:done:

2021-10-01 14:04 UTC, jonathasbsouza commented on src/components/home/ScheduleCard.tsx
> +  }
:done:

2021-10-01 14:04 UTC, jonathasbsouza commented on src/components/home/ScheduleCard.tsx
> +    variant: string
:done:

2021-10-05 01:29 UTC, JoseRenan approved these changes
Ficou toppppppppppp @jonathasbsouza ❤️ mto obg!!!!!

2021-10-05 01:29 UTC, merged